In [4]:
student = {
  "name":"Bivhas",
  "age":20,
  "faculty":"BCE"
}
print(student)

{'name': 'Bivhas', 'age': 20, 'faculty': 'BCE'}

In [23]:
d={"name":"Dinesh","age":20,"faculty":"BCE"}

In [10]:
d["name"]

'Dinesh'

In [11]:
d["age"]

20

In [12]:
d["faculty"]

'BCE'

In [18]:
d.get("name")

'Dinesh'

In [24]:
d["location"]="Sitapaila"
print(d)

{'name': 'Dinesh', 'age': 20, 'faculty': 'BCE', 'location': 'Sitapaila'}

In [25]:
d["name"]="Dinesh Gurung"
print(d)

{'name': 'Dinesh Gurung', 'age': 20, 'faculty': 'BCE', 'location': 'Sitapaila'}

In [26]:
del d["location"]
print(d)

{'name': 'Dinesh Gurung', 'age': 20, 'faculty': 'BCE'}

In [28]:
d.pop("age")
print(d)

{'name': 'Dinesh Gurung'}

In [29]:
d.popitem()
print(d)

{}

In [31]:
d={"name":"Razak","age":20,"faculty":"BCE"}
print(d)

{'name': 'Razak', 'age': 20, 'faculty': 'BCE'}

In [33]:
d.clear()
print(d)

{}

In [34]:
c={"name":"Sudeep","age":20,"faculty":"BCE"}
d=c.copy()
print(d)

{'name': 'Sudeep', 'age': 20, 'faculty': 'BCE'}

In [35]:
d.keys()

dict_keys(['name', 'age', 'faculty'])

In [36]:
d.values()

dict_values(['Sudeep', 20, 'BCE'])

In [37]:
d.items()

dict_items([('name', 'Sudeep'), ('age', 20), ('faculty', 'BCE')])

In [40]:
"name" in d

True

In [41]:
"location" in d

False

In [56]:
for k in d:
  print(k)

name
age
faculty

In [55]:
for v in d.values():
  print(v)

Sudeep
20
BCE

In [58]:
for k,v in d.items():
  print(k,v)

name Sudeep
age 20
faculty BCE

In [61]:
import pandas as pd

In [87]:
d={
    "name":["Dinesh","Bivhas","Jikmet","Sudeep","Sworup","Sangat"],
    "age":[22,20,21,25,23,32],
    "marks":[70,72,80,90,75,73]
}
df=pd.DataFrame(d)

In [88]:
df.head()

     name  age  marks
0  Dinesh   22     70
1  Bivhas   20     72
2  Jikmet   21     80
3  Sudeep   25     90
4  Sworup   23     75

In [89]:
df.tail()

     name  age  marks
1  Bivhas   20     72
2  Jikmet   21     80
3  Sudeep   25     90
4  Sworup   23     75
5  Sangat   32     73

In [90]:
df.shape

(6, 3)

In [91]:
df.columns

Index(['name', 'age', 'marks'], dtype='object')

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      object
 1   age     6 non-null      int64
 2   marks   6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes

In [93]:
df.describe()

             age      marks
count   6.000000   6.000000
mean   23.833333  76.666667
std     4.355074   7.366591
min    20.000000  70.000000
25%    21.250000  72.250000
50%    22.500000  74.000000
75%    24.500000  78.750000
max    32.000000  90.000000

In [94]:
df['name']

0    Dinesh
1    Bivhas
2    Jikmet
3    Sudeep
4    Sworup
5    Sangat
Name: name, dtype: object

In [96]:
df[['name','marks']]

     name  marks
0  Dinesh     70
1  Bivhas     72
2  Jikmet     80
3  Sudeep     90
4  Sworup     75
5  Sangat     73

In [98]:
df.iloc[1]

name     Bivhas
age          20
marks        72
Name: 1, dtype: object

In [99]:
df.loc[1]

name     Bivhas
age          20
marks        72
Name: 1, dtype: object

In [100]:
df.loc[0,'name']

'Dinesh'

In [101]:
df[df['marks']>80]

     name  age  marks
3  Sudeep   25     90

In [102]:
df[(df['age']>20)&(df['marks']>70)]

     name  age  marks
2  Jikmet   21     80
3  Sudeep   25     90
4  Sworup   23     75
5  Sangat   32     73

In [104]:
# add grade column to df
df['Grade']=['B','B','A','B','B','B']

In [105]:
print(df)

     name  age  marks Grade
0  Dinesh   22     70     B
1  Bivhas   20     72     B
2  Jikmet   21     80     A
3  Sudeep   25     90     B
4  Sworup   23     75     B
5  Sangat   32     73     B

In [106]:
#Add marks of all by 5
df['marks']=df['marks']+5

In [114]:
#Change Marks
df.loc[df['name']=='Dinesh','marks']=80

In [115]:
#Remove age column
df.drop('age',axis=1)

     name  marks Grade
0  Dinesh     80     B
1  Bivhas     85     B
2  Jikmet     85     A
3  Sudeep     95     B
4  Sworup     80     B
5  Sangat     78     B

In [116]:
#Remove 1st row of te dataframe
df.drop(0,axis=0)

     name  age  marks Grade
1  Bivhas   20     85     B
2  Jikmet   21     85     A
3  Sudeep   25     95     B
4  Sworup   23     80     B
5  Sangat   32     78     B

In [118]:
#arranging values (marks) in ascending order
df.sort_values('marks')

     name  age  marks Grade
5  Sangat   32     78     B
0  Dinesh   22     80     B
4  Sworup   23     80     B
1  Bivhas   20     85     B
2  Jikmet   21     85     A
3  Sudeep   25     95     B

In [119]:
#arranging values (marks) in descending order
df.sort_values('marks',ascending=False)

     name  age  marks Grade
3  Sudeep   25     95     B
1  Bivhas   20     85     B
2  Jikmet   21     85     A
0  Dinesh   22     80     B
4  Sworup   23     80     B
5  Sangat   32     78     B

In [121]:
c={
    "name":["Gautam","Dindayal","Dikshant","Hari","Ashim","Avash"],
    "age":[22,20,21,25,23,32],
    "marks":[70,72,80,90,75,73]
}
df1=pd.DataFrame(c)

In [122]:
pd.concat([df1,df])

       name  age  marks Grade
0    Gautam   22     70   NaN
1  Dindayal   20     72   NaN
2  Dikshant   21     80   NaN
3      Hari   25     90   NaN
4     Ashim   23     75   NaN
5     Avash   32     73   NaN
0    Dinesh   22     80     B
1    Bivhas   20     85     B
2    Jikmet   21     85     A
3    Sudeep   25     95     B
4    Sworup   23     80     B
5    Sangat   32     78     B

In [123]:
df.to_csv('file.csv')

In [125]:
pd.read_excel('file.xlsx')

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Budget Spreadsheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Thank you for using our spreadsheet! Let's gui...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,CLICK HERE for a video showing how to use the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,We also have a free app!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,The app does everything this spreadsheet does ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,Download the free app,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,1) Period,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,The first step is to figure out the period of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,(When does your budget start and how far are w...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,You can start on any day of the week or month.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,The end should usually be a year or two into t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,*The budget doesn't actually end on that date....,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,*Just type in the start date and the number of...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,Start,2026-05-08 00:00:00,NaN,NaN,NaN,NaN,NaN,Currency
21,NaN,NaN,NaN,Weeks,104,NaN,NaN,NaN,NaN,NaN,Dollar
22,NaN,NaN,NaN,Years,2,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,End,2028-05-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,--> Follow the tabs along the bottom for the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Copyright 2026 The Happy Giraffe Company. All ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [126]:
df.to_excel('file.xlsx')